name: Johnny Ryan
slackline: better engineers build better code. be a better engineer

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments: true

excerpt_separator: "<linebreak>"

# This is the default format. 
# For more see: http://jekyllrb.com/docs/permalinks/
#permalink: /:categories/:year/:month/:day/:title 
permalink: /:title 

# Comments System
# This is the key for the Disqus comments system. Get one from http://disqus.com/
disqus_shortname: jnyryangithubio

# Contact Form
# The api key for getsimpleform. Get one from http://getsimpleform.com
contactform_enabled: true 
contactform_apitoken: f70a375b83a60ecfafe284aec39cd227


# Google Analytics
analytics_enabled: true
analytics_key: UA-13112699-11
analytics_site: jnyryan.github.io

# Heroku Deployment
# Exclude files that are used for deployment (in this case deploying to Heroku)
exclude:  [ Gemfile, Gemfile.lock, Procfile, vendor]